### ISSUE TITLE
Replace WebClient with HttpClient

### ISSUE THREAD

**Issue by frg2089** [CnCNet/xna-cncnet-client#515]
> The following APIs are marked as obsolete, starting in .NET 6. Using them in code generates warning SYSLIB0014 at compile time.

[SYSLIB0014 - Microsoft Learn](https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib0014)

Add [System.Net.Http.Json](https://www.nuget.org/packages/System.Net.Http.Json) package to polyfill [`GetFromJsonAsync`](https://learn.microsoft.com/dotnet/api/system.net.http.json.httpclientjsonextensions.getfromjsonasync?view=net-8.0) methods.

like this:

https://github.com/CnCNet/xna-cncnet-client/blob/f89c8fcdb0008bac7b7e205d561544e000340373/DXMainClient/Domain/Multiplayer/CnCNet/CnCNetPlayerCountTask.cs#L53-L80
```csharp
// TODO: Cached it!
// See https://learn.microsoft.com/dotnet/api/system.net.http.httpclient.-ctor?view=net-8.0#remarks
HttpClient client = new();
// TODO: make it async.
var infos = client.GetFromJsonAsync<Dictionary<string, int>>("http://api.cncnet.org/status").Result;
if (!infos.TryGetValue(cncnetLiveStatusIdentifier, out int numGames))
    numGames = -1;

return numGames;
```

## TODO
- [ ] CnCNetPlayerCountTask https://github.com/CnCNet/xna-cncnet-client/blob/f89c8fcdb0008bac7b7e205d561544e000340373/DXMainClient/Domain/Multiplayer/CnCNet/CnCNetPlayerCountTask.cs#L53
- [ ] ExtendedWebClient https://github.com/CnCNet/xna-cncnet-client/blob/3a2dac0f2858af94e21af1146673d34ae0b5e436/DXMainClient/Domain/Multiplayer/CnCNet/CnCNetTunnel.cs#L101 https://github.com/CnCNet/xna-cncnet-client/blob/d7e370ab6cc9bd63417d5e1e55b09aa52dd4f06e/DXMainClient/Domain/Multiplayer/CnCNet/ExtendedWebClient.cs#L9
- [ ] TWebClient https://github.com/CnCNet/xna-cncnet-client/blob/6ff904f8560f063c1e3ffd0114a68d894b316398/DXMainClient/Domain/Multiplayer/CnCNet/MapSharer.cs#L381 https://github.com/CnCNet/xna-cncnet-client/blob/6ff904f8560f063c1e3ffd0114a68d894b316398/DXMainClient/Domain/Multiplayer/CnCNet/MapSharer.cs#L446
- [ ] TunnelHandler https://github.com/CnCNet/xna-cncnet-client/blob/f89c8fcdb0008bac7b7e205d561544e000340373/DXMainClient/Domain/Multiplayer/CnCNet/TunnelHandler.cs#L156

**Comment by SadPencil** [comment]
This is an insightful suggestion. It was partially implemented in https://github.com/CnCNet/xna-cncnet-client/pull/976
